@base = http://localhost:5000/api/v1
@contentType = application/json


GET {{base}} HTTP/1.1

### New Subcription
POST  {{base}}/subscribe HTTP/1.1
Content-Type: {{contentType}}

{
 "email": "Nsovo@gmail.com",
 "preferences": "1d"
}


### Update Subcription
PUT  {{base}}/subscription/649ee893638c9f3339caf6e5 HTTP/1.1
Content-Type: {{contentType}}

{
    "preferences": "1d"
}

### Get All Subcriptions
GET {{base}}/subscription HTTP/1.1


### Get All Temp Subcriptions
GET {{base}}/subscription/all HTTP/1.1


### Delete Subcription
DELETE {{base}}/subscription/649ee63da65de0dc1829f893 HTTP/1.1
